In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [2]:
from sklearn.datasets import make_classification
x,y=make_classification(n_samples=1000,n_features=3,n_redundant=1,n_classes=2,random_state=42)

In [3]:
print(x,y)

[[ 2.48547786  2.39963589 -1.46526917]
 [ 2.20403962 -1.06965652  0.00979545]
 [-0.5726534  -0.75494788  0.42032991]
 ...
 [-0.41608875  0.46668963 -0.11024494]
 [-1.57936997  2.48498245 -0.71060102]
 [-0.43277356  0.89093028 -0.28069604]] [1 0 0 1 1 0 0 1 1 0 1 0 0 1 0 0 0 1 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 1 0 1 1
 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1 0 0 0 1 0
 0 1 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 1 1 1 0 1 1 0 0 0 0 1 1 0 1 1 0 0 1 0 0
 1 0 1 1 1 0 0 1 0 0 1 1 1 0 1 1 1 1 1 0 0 0 1 1 1 0 1 0 0 0 0 1 0 0 0 0 0
 1 0 0 0 0 1 0 0 1 1 0 1 0 0 1 1 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1
 1 1 0 1 1 0 1 0 0 1 1 1 1 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 1 1 1 1 1 0 0
 0 0 0 0 0 1 0 1 1 1 1 1 0 0 0 0 1 0 1 0 0 0 1 1 0 0 0 0 1 1 0 1 1 1 0 0 0
 0 1 1 1 0 1 1 0 1 0 0 1 0 1 0 0 0 0 0 1 0 1 1 1 1 0 0 0 1 1 0 0 1 1 1 0 0
 1 1 0 1 1 0 0 1 1 1 0 1 0 1 0 1 0 1 0 0 0 1 1 0 0 0 1 0 0 0 0 0 1 1 0 1 0
 0 0 1 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 1 0 0 0 1 1 1 1 1 1 0 0 1 0 1 0 1 1
 0 0 0 1 1

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error,r2_score
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)
knn=KNeighborsRegressor(n_neighbors=2)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
print("Mean Squared Error : ",mean_squared_error(y_test,y_pred))
print("R2 Score : ",r2_score(y_test,y_pred))

Mean Squared Error :  0.07416666666666667
R2 Score :  0.7033201475621138
